version: "2"
services:
  app:
    image: germanium/babylo
    container_name: babylo
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./database_data/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
