babystat_accueil:
    path:     /
    defaults: { _controller: BabyStatBundle:Stat:index }

babystat_joueur:
    path:     /player
    defaults: { _controller: BabyStatBundle:Stat:player }

babystat_joueurstat:
    path:     /morestat
    defaults: { _controller: BabyStatBundle:Stat:morestat }

babystat_playerstatgraph:
    path:     /playerstatgraph
    defaults: { _controller: BabyStatBundle:Stat:playerstatgraph }

babystat_pagejoueur:
    path:     /playerstat
    defaults: { _controller: BabyStatBundle:Stat:playerstat }

babystat_partie:
    path:     /game
    defaults: { _controller: BabyStatBundle:Stat:game }

babystat_schedule:
    path:     /schedule
    defaults: { _controller: BabyStatBundle:Stat:schedule }

babystat_changeSchedule:
    path:     /changeSchedule
    defaults: { _controller: BabyStatBundle:Stat:changeSchedule }

babystat_nbpartie:
    path:     /nbgame
    defaults: { _controller: BabyStatBundle:Stat:nbgame }

babystat_ajoutpartie:
    path:     /admin/addgame
    defaults: { _controller: BabyStatBundle:Stat:addgame }

babystat_savepartie:
    path:     /admin/savegame
    defaults: { _controller: BabyStatBundle:Stat:savegame }

babystat_matchmaker:
    path:     /matchmaker
    defaults: { _controller: BabyStatBundle:Stat:matchmaker }

babystat_matchmaking:
    path:     /matchmaking
    defaults: { _controller: BabyStatBundle:Stat:matchmaking }

babystat_delgame:
    path:     /admin/delgame
    defaults: { _controller: BabyStatBundle:Stat:delgame }

babystat_useradmin:
    path:     /superadmin/useradmin
    defaults: { _controller: BabyStatBundle:Stat:useradmin }

babystat_saveuser:
    path:     /superadmin/saveuser
    defaults: { _controller: BabyStatBundle:Stat:saveuser }