babystat_accueil:
    path:     /
    defaults: { _controller: BabyStatBundle:Stat:index }

babystat_joueur:
    path:     /player
    defaults: { _controller: BabyStatBundle:Stat:player }

babystat_joueurstat:
    path:     /morestat
    defaults: { _controller: BabyStatBundle:Stat:morestat }

babystat_playerstatgraph:
    path:     /playerstatgraph
    defaults: { _controller: BabyStatBundle:Stat:playerstatgraph }

babystat_pagejoueur:
    path:     /playerstat
    defaults: { _controller: BabyStatBundle:Stat:playerstat }

babystat_partie:
    path:     /game
    defaults: { _controller: BabyStatBundle:Stat:game }

babystat_nbpartie:
    path:     /nbgame
    defaults: { _controller: BabyStatBundle:Stat:nbgame }

babystat_ajoutpartie:
    path:     /addgame
    defaults: { _controller: BabyStatBundle:Stat:addgame }

babystat_savepartie:
    path:     /savegame
    defaults: { _controller: BabyStatBundle:Stat:savegame }
