login:
    path:   /login
    defaults: { _controller: BabyUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

baby_stat:
    resource: "@BabyStatBundle/Resources/config/routing.yml"
    prefix:   /