security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Baby\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1


    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Baby\UserBundle\Entity\User, property: username }

    firewalls:
        main:
            remember_me:
                key:		"babylol"
                lifetime:	2592000
                path:		/
                domain:		~
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/superadmin/.*, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/.*, roles: [ROLE_ADMIN] }
        - { path: ^/playerstat, roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_REMEMBERED] }
        - { path: ^/.*, roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_REMEMBERED] } #comment this line for public mode
